### ISSUE TITLE
Porting to Netbeans 11

### ISSUE THREAD

**Issue by offa** [offa/NB-CMake-Completion#17]
Porting to Netbeans 11.

**Comment by wltjr** [comment]
I am happy to help with this in any way I can. Which maybe limited to just testing. I have this module in Netbeans 9 snapshot that works fine, the one made for 8.2. I also am working on building Netbeans 9 from source on Gentoo. I have this module [packaged](https://github.com/Obsidian-StudiosInc/os-xtoo/tree/master/nb-plugins/nb-cmake-completion) and added to my [Netbeans package](https://github.com/Obsidian-StudiosInc/os-xtoo/blob/master/dev-util/netbeans/netbeans-9999.ebuild#L154). But it does not work correctly, no syntax highlighting, etc. Either something I am missing, or needs changes in code

I just tried a live version using the latest head from master. I did not see any difference with that and the tagged version 0.1.2. Not sure what needs to be modified if anything. The one for 8.2 seems to work fine in Netbeans 9. Not sure why the one I have build from source does not work. Could be due to some other stuff.

**Comment by offa** [comment]
> But it does not work correctly, no syntax highlighting, etc. Either something I am missing, or needs changes in code

I had some trouble with NB9 Snapshots too. Eg. UI elements didn't work correctly; I experienced issues with other plugins too. This looks like a general problem with the current NB9 versions (or at least with those I've used so far) or is somehow related to JDK9 probably.

The CMake syntax highlighting is not provided by this plugin and ships with NetBeans. So either there's something broken in the current NB9 snapshots or this plugin affects the syntax highlighting. I wouldn't expect the latter, but better check this … just to be sure: Do you experience the broken highlighting without the CMake Completion and can you see any information regarding this in the IDE Log?

> I just tried a live version using the latest head from master. I did not see any difference with that and the tagged version 0.1.2. Not sure what needs to be modified if anything. The one for 8.2 seems to work fine in Netbeans 9. Not sure why the one I have build from source does not work. 

So building _v0.1.2_ (or _master_) from sources causes problems, but using the compiled NBM (provided by the Updater / Plugin Center) works?

Can you see any errors or warnings related to this plugin in the build and/or IDE logs? Want what JDK are you using?

Btw. thanks for your input! 👍

**Comment by wltjr** [comment]
Sorry just to be clear. I have no issues with the plugin/module binary NBM from update manager in NB 9 snapshot binaries running on JDK 9. I have never had any issues from this plugin/module in any NB binaries, 9 snapshots or 8.2. Though maybe issues I did not run into yet.

It is in my own NB 9 from source packages I have issues, [main ide packages](https://github.com/Obsidian-StudiosInc/os-xtoo/tree/master/nb-ide/) and [plugin packages](https://github.com/Obsidian-StudiosInc/os-xtoo/tree/master/nb-plugins/). That is using beta-rc3. I think many things have been fixed since that tag/release. Which may have addressed the issue I am having not sure.

In my from source NB 9 package, I have syntax highlighting working in general, java, css, html, javascript, etc. [Flow markdown plugin](https://github.com/madflow/flow-netbeans-markdown) seems to work as good as it does normally using [my flow markdown package](https://github.com/Obsidian-StudiosInc/os-xtoo/tree/master/nb-plugins/flow-netbeans-markdown), and some other stuff. Just when I open a cmake file, its regular text. Not like when I open it in NB 9 snapshot binaries. So seems something is off with my Netbeans package from source, or my [cmake plugin package](https://github.com/Obsidian-StudiosInc/os-xtoo/tree/master/nb-plugins/nb-cmake-completion) from source.

I have not tried to use my from source version of this plugin/module in NB 9 Snapshot. I always use the one from update center. I can try replacing it with the one I have built from source to see if that is the issue. If it works then I know the problem is in Netbeans, not the cmake module/plugin I built from source.

In my Netbeans 9 from source, I tried both _v0.1.2_ and master. I did not see any difference. Thus the problem maybe somewhere else in NB 9. Or something else.

I do not get any errors from this module. I get some general git errors that maybe related, but the stack trace does not lead back to this module. I do not think that is related or why I do not get syntax highlighting and the rest for cmake files. I can provide that log file if you would like to take a look. I am pretty 100% nothing specific to this module/plugin is being logged. It is strange.

I am on Oracle JDK 9.0.4. I will be moving on to 10 and 11 soon. May skip 10 for 11, not sure.

**Comment by wltjr** [comment]
Here is a log file when I open a CMakeLists.txt file. The git output maybe related not sure.[messages.log](https://github.com/offa/NB-CMake-Completion/files/1843530/messages.log). The other exceptions are from nb-darcula, and are normal. Since I do not have those modules.

**Comment by offa** [comment]
> I am pretty 100% nothing specific to this module/plugin is being logged.

That's right. But the line _"This code should have never made it into slf4j-api.jar"_ is funny. 😄

**Comment by wltjr** [comment]
Yes I need to track that down. I thought it was funny as well! Code should not have made it, but clearly did... I am assuming something else in the IDE. I do not think cmake syntax highlighting works if I install via plugin manger in my from source build of NB 9. Either something is off in my build, I am missing another module, or some bug in NB 9 thats been fixed. Thus not seeing the issue in snapshot binaries of NB 9.

**Comment by wltjr** [comment]
Its semi moot for now, as the sources for the C/C++ modules/plugins have not been donated from Oracle to Apache yet. So even when I get this working in my build. I will still be missing sytnax support for C projects I use CMake for. :face_with_head_bandage:

**Comment by offa** [comment]
There's no first-class C/C++ support yet. I'll close here for now and we'll see, what feature NB releases support.
